trigger:
- master
- develop
- release

variables:
  latestBackendGitRevision: HEAD~1
  latestFrontendGitRevision: HEAD~1
  latestClientGitRevision: HEAD~1
  isMasterBranch: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  isDevelopBranch: eq(variables['Build.SourceBranch'], 'refs/heads/developer')
  isReleaseBranch: eq(variables['Build.SourceBranch'], 'refs/heads/release')
  isPullRequest: eq(variables['Build.Reason'], 'PullRequest')
  dockerHubId: kochanowski
  dockerHubImageName: maisie

jobs:
- job: Facts
  displayName: Gather facts
  pool:
    vmImage: 'Ubuntu-16.04'
  variables:
    maisieVersionType: patch
    sourceBranch: $[ variables['Build.SourceBranchName'] ]
    rebuildBackend: 0
    rebuildFrontend: 0
    rebuildClient: 0
  
  steps:
  - bash: |
      git checkout $(sourceBranch)
      git diff-index $(latestBackendGitRevision) --quiet -- backend/
      echo "##vso[task.setvariable variable=rebuildBackend]$?"
    displayName: Check for changes in Backend component

  - bash: echo "##vso[task.setvariable variable=rebuildBackend]1"
    condition: eq(variables['forceRebuildBackend'], 'True')
    displayName: Overwrite the rebuildBackend flag

  - bash: |
      git checkout $(sourceBranch)
      git diff-index $(latestFrontendGitRevision) --quiet -- frontend/
      echo "##vso[task.setvariable variable=rebuildFrontend]$?"
    displayName: Check for changes in Frontend component

  - bash: echo "##vso[task.setvariable variable=rebuildFrontend]1"
    condition: eq(variables['forceRebuildFrontend'], 'True')
    displayName: Overwrite the rebuildFrontend flag

  - bash: |
      git checkout $(sourceBranch)
      git diff-index $(latestClientGitRevision) --quiet -- client/
      echo "##vso[task.setvariable variable=rebuildClient]$?"
    displayName: Check for changes in Client component

  - bash: echo "##vso[task.setvariable variable=rebuildClient]1"
    condition: eq(variables['forceRebuildClient'], 'True')
    displayName: Overwrite the rebuildClient flag

  - bash: echo "##vso[task.setvariable variable=maisieVersionType]minor"
    condition: eq(variables['isMasterBranch'], 'True')
    displayName: Set version type (Master)

  - bash: echo "##vso[task.setvariable variable=maisieVersionType]major"
    condition: eq(variables['isReleaseBranch'], 'True')
    displayName: Set version type (Release)
  
  - bash: |
      echo "##vso[task.setvariable variable=maisieVersionType;isOutput=true]$(maisieVersionType)"
      echo "##vso[task.setvariable variable=rebuildBackend;isOutput=true]$(rebuildBackend)"
      echo "##vso[task.setvariable variable=rebuildFrontend;isOutput=true]$(rebuildFrontend)"
      echo "##vso[task.setvariable variable=rebuildClient;isOutput=true]$(rebuildClient)"
    name: factsVars
    displayName: Publish variables

- job: VerifyFacts
  displayName: Verify gathered facts
  dependsOn: Facts
  pool:
    vmImage: 'Ubuntu-16.04'
  variables:
    maisieVersionType: $[ dependencies.Facts.outputs['factsVars.maisieVersionType'] ]
    rebuildBackend: $[ dependencies.Facts.outputs['factsVars.rebuildBackend'] ]
    rebuildFrontend: $[ dependencies.Facts.outputs['factsVars.rebuildFrontend'] ]
    rebuildClient: $[ dependencies.Facts.outputs['factsVars.rebuildClient'] ]

  steps:
  - script: |
      echo maisieVersionType $(maisieVersionType)
      echo latestClientGitRevision $(latestClientGitRevision)
      echo latestBackendGitRevision $(latestBackendGitRevision)
      echo latestFrontendGitRevision $(latestFrontendGitRevision)
      echo rebuildClient $(rebuildClient)
      echo rebuildBackend $(rebuildBackend)
      echo rebuildFrontend $(rebuildFrontend)
    displayName: Display the summary of variables

- job: BuildClient
  displayName: Build Client - PyPI Package
  dependsOn: Facts
  condition: eq(dependencies.Facts.outputs['factsVars.rebuildClient'], '1')
  pool: 
    vmImage: 'Ubuntu-16.04'
  variables:
    maisieVersionType: $[ dependencies.Facts.outputs['factsVars.maisieVersionType'] ]

  steps:
  - bash: |
      pip3 install --upgrade pip 
      pip3 install --upgrade wheel 
      pip3 install --upgrade pre-commit
      pre-commit install
      find client -type f -name '*.py' | xargs pre-commit run --files
    displayName: Apply pre-commit hooks
  
  - bash: |
      export UNVME_MAISIE=$(curl -s https://unversion.me/@kochanowski/maisie/pypi/client/$(maisieVersionType)/)
      echo "##vso[task.setvariable variable=maisieVersion]$UNVME_MAISIE"
    displayName: Get version number for the next release
  
  - script: |
      pip install -r requirements.txt
    displayName: Install dependencies

  - script: |
      pip install pytest pytest-azurepipelines
      # pytest
    displayName: Test package

  - bash: |
      pip install --user bumpversion
      export CURRENT_VERSION=$(python client/setup.py --version)
      bumpversion --current-version $CURRENT_VERSION --new-version $(maisieVersion) --allow-dirty --no-commit --no-tag --list $(maisieVersionType) setup.py
    displayName: Apply version patch for client configuration

  - script: |
      pip install twine
      python setup.py sdist bdist_wheel
      twine check dist/*
    displayName: 'Build package'

  - task: TwineAuthenticate@0
    inputs:
      externalFeeds: 'PyPI-UnversionMe'

  - script: 'twine upload -r PyPI-UnversionMe --config-file $(PYPIRC_PATH) dist/*'
    displayName: Publish to PyPI
    condition: not(variables['isPullRequest'])

  - bash: curl -s https://unversion.me/listener/$(unvmeClientListener)/$(maisieVersion)/
    displayName: Call Unversion.me for the new release
    condition: not(variables['isPullRequest'])

- job: BuildBackend
  displayName: Build Backend - DockerHub
  dependsOn: Facts
  condition: eq(dependencies.Facts.outputs['factsVars.rebuildBackend'], '1')
  pool:
    vmImage: 'Ubuntu-16.04'
  variables:
    maisieVersionType: $[ dependencies.Facts.outputs['factsVars.maisieVersionType'] ]

  steps:
  - bash: |
      pip3 install --upgrade pip 
      pip3 install --upgrade wheel 
      pip3 install --upgrade pre-commit
      pre-commit install
      find backend -type f -name '*.py' | xargs pre-commit run --files
    displayName: Apply pre-commit hooks

  - bash: |
      export UNVME_MAISIE=$(curl -s https://unversion.me/@kochanowski/maisie/dockerhub/backend/$(maisieVersionType)/)
      echo "##vso[task.setvariable variable=maisieVersion]$UNVME_MAISIE"
    displayName: Get version number for the next release

  - script: |
      echo "Building backend image version $(maisieVersion)"
      docker login -u $(dockerHubId) -p $password 
      docker build -t $(dockerHubId)/$(dockerHubImageName):backend -t $(dockerHubId)/$(dockerHubImageName):backend-$(maisieVersion) -f Dockerfile.production .
    env:
      password: $(dockerHubPassword)
    displayName: Build new image
      
  - script: |
      docker push $(dockerHubId)/$(dockerHubImageName):backend
      docker push $(dockerHubId)/$(dockerHubImageName):backend-$(maisieVersion) && curl -s https://unversion.me/listener/$(unvmeBackendListener)/$(maisieVersion)/
    displayName: Push built image
    condition: not(variables['isPullRequest'])

- job: BuildFrontend
  displayName: Build Frontend - DockerHub
  dependsOn: Facts
  condition: eq(dependencies.Facts.outputs['factsVars.rebuildFrontend'], '1')
  pool:
    vmImage: 'Ubuntu-16.04'
  variables:
    maisieVersionType: $[ dependencies.Facts.outputs['factsVars.maisieVersionType'] ]

  steps:
  - bash: |
      export UNVME_MAISIE=$(curl -s https://unversion.me/@kochanowski/maisie/dockerhub/frontend/$(maisieVersionType)/)
      echo "##vso[task.setvariable variable=maisieVersion]$UNVME_MAISIE"
    displayName: Get version number for the next release

  - script: |
      echo "Building frontend image version $(maisieVersion)"
      docker login -u $(dockerHubId) -p $password 
      docker build -t $(dockerHubId)/$(dockerHubImageName):frontend -t $(dockerHubId)/$(dockerHubImageName):frontend-$(maisieVersion) -f Dockerfile.production .
    env:
      password: $(dockerHubPassword)
    displayName: Build new image

  - script: |
      docker push $(dockerHubId)/$(dockerHubImageName):frontend
      docker push $(dockerHubId)/$(dockerHubImageName):frontend-$(maisieVersion) && curl -s https://unversion.me/listener/$(unvmeFrontendListener)/$(maisieVersion)/
    displayName: Push built image
    condition: not(variables['isPullRequest'])
