version: "3"
services:
  backend:
    build:
      context: ./backend/
    command: "./development.sh"
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - postgresdb

  frontend:
    build:
      context: ./frontend/
    command: "yarn start"
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    # volumes:
    # - ./frontend:/app

  postgresdb:
    image: postgres:11.2
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
