version: '3'
services:
  backend:
    build:
      context: ./backend/
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ./backend/:/app

  database:
    image: postgres:11.2
    restart: always
    environment:
      POSTGRES_PASSWORD: localdev
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"