version: "3"
services:
  backend:
    container_name: maisie_backend
    build:
      context: ./backend/
    command: "./development.sh"
    image: kochanowski/maisie:backend
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - postgresdb

  frontend:
    container_name: maisie_frontend
    build: 
      context: ./frontend/
    command: "yarn start"
    image: kochanowski/maisie:frontend
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  postgresdb:
    container_name: maisie_postgresdb
    image: postgres:11.2
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
